### ISSUE TITLE
Scala 2.12 publish

### ISSUE THREAD

**Issue by pjfanning** [nikita-volkov/embrace#2]
Would it be possible to publish a scala 2.12 compatible jar? This would be a prerequisite to publishing a 2.12 compatible sorm jar.

**Comment by pjfanning** [comment]
Even if the same jar works in scala 2.12, the pom.xml has an upper bound for scala of 2.11.999.

**Comment by nikita-volkov** [comment]
Is it not already?

**Comment by nikita-volkov** [comment]
I mean the version bound is `[2.10,3)`

**Comment by pjfanning** [comment]
Apologies, I copied the comment from sext project.
